import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { useProjectStore } from '../stores/projectStore'
import { useTagFilterStore } from '../stores/tagFilterStore'
import { formatNumber } from '../utils/formatting'
import { biggestGap, scoredDimensions } from '../utils/healthBreakdown'

function scoreColor(score: number): string {
  if (score >= 80) return 'text-success'
  if (score >= 60) return 'text-warning'
  return 'text-danger'
}

export function Overview() {
  const { data } = useProjectStore()
  const navigate = useNavigate()
  const { selected: tagSelected, mode: tagMode } = useTagFilterStore()

  const filteredModels = useMemo(() => {
    if (!data) return []
    const all = Object.values(data.models)
    if (tagSelected.size === 0) return all
    return all.filter(m => {
      const hasMatch = m.tags.some(t => tagSelected.has(t))
      return tagMode === 'include' ? hasMatch : !hasMatch
    })
  }, [data, tagSelected, tagMode])

  if (!data) return null

  const modelCount = Object.keys(data.models).length
  const sourceCount = Object.keys(data.sources).length
  const seedCount = Object.keys(data.seeds).length
  const testCount = Object.values(data.models).reduce(
    (sum, m) => sum + m.test_results.length, 0
  )
  const passingTests = Object.values(data.models).reduce(
    (sum, m) => sum + m.test_results.filter(t => t.status === 'pass').length, 0
  )

  const gap = biggestGap(data.health)

  const stats = [
    { label: 'Models', value: modelCount, color: 'text-primary' },
    { label: 'Sources', value: sourceCount, color: 'text-success' },
    { label: 'Seeds', value: seedCount, color: 'text-neutral' },
    { label: 'Tests', value: testCount, sublabel: `${passingTests} passing`, color: 'text-success' },
  ]

  return (
    <div className="max-w-4xl">
      <h1 className="text-2xl font-bold mb-1">{data.metadata.project_name}</h1>
      <p className="text-[var(--text-muted)] text-sm mb-6">
        Generated by docglow v{data.metadata.docglow_version}
        {' '}&middot; dbt v{data.metadata.dbt_version}
      </p>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        {stats.map((stat) => (
          <div key={stat.label}
               className="border border-[var(--border)] rounded-lg p-4 bg-[var(--bg-surface)]">
            <div className={`text-2xl font-bold ${stat.color}`}>
              {formatNumber(stat.value)}
            </div>
            <div className="text-sm text-[var(--text-muted)]">{stat.label}</div>
            {stat.sublabel && (
              <div className="text-xs text-[var(--text-muted)] mt-1">{stat.sublabel}</div>
            )}
          </div>
        ))}
      </div>

      {/* Health Summary */}
      <div
        className="mb-8 p-4 border border-[var(--border)] rounded-lg bg-[var(--bg-surface)]
                   cursor-pointer hover:border-primary/30 transition-colors"
        onClick={() => navigate('/health')}
      >
        <div className="flex items-start justify-between gap-6">
          <div>
            <h2 className="text-sm font-medium text-[var(--text-muted)] mb-1">Project Health</h2>
            <div className="flex items-baseline gap-2">
              <span className={`text-3xl font-bold ${
                data.health.score.grade === 'A' ? 'text-success' :
                data.health.score.grade === 'B' ? 'text-primary' :
                data.health.score.grade === 'C' ? 'text-warning' : 'text-danger'
              }`}>
                {data.health.score.grade}
              </span>
              <span className="text-lg text-[var(--text-muted)]">
                {data.health.score.overall.toFixed(0)}/100
              </span>
            </div>
          </div>
          {/* The dimensions the grade is actually made of. Showing model-level
              coverage here instead reads as a contradiction — 100% documented
              next to a B — because column coverage is what moves the score. */}
          <div className="flex gap-5 text-xs text-[var(--text-muted)] pt-1">
            {scoredDimensions(data.health).map(dim => (
              <div key={dim.key} className="text-right">
                <div className={`font-medium ${scoreColor(dim.score)}`}>
                  {dim.score.toFixed(0)}
                </div>
                <div>{dim.label}</div>
              </div>
            ))}
          </div>
        </div>
        {gap && (
          <p className="mt-3 pt-3 border-t border-[var(--border)] text-xs text-[var(--text-muted)]">
            <span className="text-[var(--text)] font-medium">{gap.label}</span>
            {' is the biggest gap — '}{gap.detail}.
          </p>
        )}
      </div>

      <div className="flex items-baseline gap-2 mb-3">
        <h2 className="text-lg font-semibold">
          {tagSelected.size > 0 ? 'Filtered Models' : 'Recent Models'}
        </h2>
        {tagSelected.size > 0 && (
          <span className="text-xs text-[var(--text-muted)]">
            {filteredModels.length} of {modelCount}
          </span>
        )}
      </div>
      <div className="border border-[var(--border)] rounded-lg overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-[var(--bg-surface)]">
            <tr>
              <th className="text-left px-4 py-2 font-medium">Model</th>
              <th className="text-left px-4 py-2 font-medium">Materialization</th>
              <th className="text-left px-4 py-2 font-medium">Columns</th>
              <th className="text-left px-4 py-2 font-medium">Tests</th>
            </tr>
          </thead>
          <tbody>
            {filteredModels.slice(0, 10).map((model) => {
              const passing = model.test_results.filter(t => t.status === 'pass').length
              const total = model.test_results.length
              return (
                <tr key={model.unique_id}
                    className="border-t border-[var(--border)] hover:bg-[var(--bg-surface)] cursor-pointer"
                    onClick={() => window.location.hash = `#/model/${encodeURIComponent(model.unique_id)}`}>
                  <td className="px-4 py-2">
                    <span className="font-medium text-primary">{model.name}</span>
                    {model.description && (
                      <p className="text-xs text-[var(--text-muted)] truncate max-w-xs">
                        {model.description}
                      </p>
                    )}
                  </td>
                  <td className="px-4 py-2 capitalize">{model.materialization}</td>
                  <td className="px-4 py-2">{model.columns.length}</td>
                  <td className="px-4 py-2">
                    {total > 0 ? (
                      <span className={passing === total ? 'text-success' : 'text-warning'}>
                        {passing}/{total}
                      </span>
                    ) : (
                      <span className="text-[var(--text-muted)]">—</span>
                    )}
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}
